[project]
name = "iron-agent"
version = "0.1.0"
description = "Required dependencies for the lead search agent to work"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "langchain==0.3.7",
    "langchain-community==0.3.7",
    "langchain-core==0.3.19",
    "langchain-openai==0.2.9",
    "pydantic>=2.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5"
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "requests-mock>=1.12.1",
]

[tool.pytest.ini_options]
pythonpath = "src"
addopts = "-v"
testpaths = ["tests"]
